version: "3.8"
services:
  matiasmlforever-githubio-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace
    working_dir: /workspace
